### ISSUE TITLE
Move client-side requests from JSONP to CORS to Update Compare app for compatibility with API 1.0 

### ISSUE THREAD

**Issue by riordan** [pelias-deprecated/compare-v1#1]
Compare utility [relies](https://github.com/pelias/compare/blob/master/app/controllers/MainController.js#L31) on JSONP/callbacks to make cross-domain requests from web clients. We are disabling JSONP requests and callback parameters with the release of the 1.0 api.

We'll have to update the compare app to support these requests.

**Comment by missinglink** [comment]
@riordan this is complete now but requires the release of https://github.com/pelias/api/pull/256 before it will work against our dev env.
