### ISSUE TITLE
API key for dev

### ISSUE THREAD

**Issue by orangejulius** [pelias-deprecated/compare-v1#12]
As of a few weeks ago, we put apiaxle in front of pelias dev to ensure it's more like production, for testing things. However now that causes the compare app to fail for dev. We need to add a dev api key just like we have one in production.

**Comment by missinglink** [comment]
it goes here: https://github.com/pelias/compare/blob/355b63237715eb059826524078e71ad60bb19b7e/app/controllers/MainController.js#L13
