### ISSUE TITLE
provide default api key in UI

### ISSUE THREAD

**Issue by missinglink** [pelias-deprecated/compare-v1#2]
I would like to hard-code an API key in to this codebase, just to make everyones life easier.

At this stage I'm not able to create keys through the developer interface and I didn't want to commit one of our team keys, so in the meantime it's set as `?api_key=pelias-YOUR_API_KEY_HERE`.

@heffergm could you please generate a key which is specifically for use in this web app?

**Comment by heffergm** [comment]
Key provided to @missinglink .
